"""
Django settings for _server project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load secret key from environment variable. Raise an error if not set.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY environment variable is not set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("1", "true", "yes")

# Hosts: provide a comma-separated list in `DJANGO_ALLOWED_HOSTS`.
# Accepts entries like "localhost,127.0.0.1,assemblock.dev,https://assemblock.dev"
raw_allowed = os.getenv("DJANGO_ALLOWED_HOSTS", "")
if raw_allowed:
    # Normalize by stripping whitespace and removing any scheme prefixes for ALLOWED_HOSTS
    ALLOWED_HOSTS = [
        h.strip().replace("http://", "").replace("https://", "")
        for h in raw_allowed.split(",")
        if h.strip()
    ]
else:
    ALLOWED_HOSTS = []

# CSRF trusted origins must include scheme (e.g. https://assemblock.dev).
# Use DJANGO_CSRF_TRUSTED_ORIGINS env var if provided, else fall back to any
# scheme-prefixed entries from DJANGO_ALLOWED_HOSTS.
raw_trusted = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
if raw_trusted:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in raw_trusted.split(",") if o.strip()]
else:
    # fall back: include any allowed-host entries that were provided with a scheme
    CSRF_TRUSTED_ORIGINS = [
        h.strip()
        for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
        if h.strip() and (h.strip().startswith("http://") or h.strip().startswith("https://"))
    ]


# Application definition

INSTALLED_APPS = [
    'core.apps.CoreConfig',
    'registration.apps.RegistrationConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE.append("core.middleware.asset_proxy_middleware")

ROOT_URLCONF = '_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# DONT USE THE STATIC URL WHEN IN DEBUG MODE
# If an asset host is configured via ASSET_URL, and we're not in DEBUG,
# build an absolute STATIC_URL pointing to that host so assets load from
# the external static host (e.g. https://static.assemblock.dev/static/).
asset_url = os.getenv("ASSET_URL", "").strip()
if asset_url and not asset_url.startswith(("http://", "https://")):
    asset_url = "https://" + asset_url

if DEBUG:
    STATIC_URL = "__UNUSED__/"
else:
    STATIC_URL = f"{asset_url.rstrip('/')}/static/" if asset_url else 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "registration/sign_in/"
