# Generated by Django 5.0.3 on 2025-12-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
