# Generated by Django 5.0.3 on 2025-12-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_script_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='settings_json',
            field=models.JSONField(default=dict),
        ),
    ]
