# Generated by Django 5.0.3 on 2026-01-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_script_settings_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
